Support PVC
timfeirg/lain-cli pull request #48
Opened 2022-05-18 11:07 UTC by hongqn

2022-05-18 12:55 UTC, timfeirg requested changes

2022-05-18 12:55 UTC, timfeirg commented on lain_cli/chart_template/values.yaml.j2
> +#  cluster-pvc:
按照先前的讨论, 出于隔离需要, 正常是不会出现集群 level 的 pvc, 都是 app level, 因此这里应该删去.

2022-05-18 12:55 UTC, timfeirg commented on lain_cli/chart_template/templates/pvc.yaml
> +apiVersion: v1
顶部应该添加用于分隔多个 yaml 文件的 `---` 分隔线, 可以参考 deployment.yaml 的顶部

2022-05-18 12:55 UTC, timfeirg commented on lain_cli/chart_template/templates/deployment.yaml
> +kind: PersistentVolumeClaim
是不是忘了删了, 该 pr 里已经有一个 pvc.yaml, 这是先前的残留代码吧?

2022-05-18 12:55 UTC, timfeirg commented on lain_cli/chart_template/values.yaml.j2
> +#     storageClassName: my-sc
不妨直接写成 juicefs-sc, 这不仅是社区常用写法, 对你团队也起到示范作用, 方便照抄.

2022-05-18 12:55 UTC, timfeirg commented on lain_cli/chart_template/values.yaml.j2
> +#         storage: 10Pi
改成合理的, 方便照抄的默认值, 比方说 1Gi 之类的

2022-05-18 12:55 UTC, timfeirg commented on lain_cli/chart_template/values.yaml.j2
> +# 在 persistentVolumeClaims 里定义的 claim 都会自动创建一个同名的 volume ，不用在这里写了。
pvc 相关的注释希望能汇聚在 pvc clause 附近, 详见 pvc 附近我的评论

2022-05-18 12:55 UTC, timfeirg commented on lain_cli/chart_template/templates/deployment.yaml
> +        - name: {{ $pvcName }}
在 volumes 下声明了 volume, 但容器要摸到这个 volume, 还需要将其挂载到容器内才行, 因此我相信还需要在 `volumeMounts` 下追加对应的挂载配置才可以

2022-05-18 12:55 UTC, timfeirg commented on lain_cli/chart_template/templates/deployment.yaml
> +            claimName: {{ $.Release.Name }}-{{ $pvcName }}
靠模板内部拼接字符串来得到 claim name, 我总觉得还不如彻底交给用户来书写, 也就是让用户直接在 values.volumes 下追加对应的 pvc.

这样做或许在教学上会遇到一些麻烦, 但我相信难度和书写 ingress 差不多, 都是需要用户理解这些资源的概念

2022-05-18 15:09 UTC, hongqn commented on lain_cli/chart_template/templates/pvc.yaml
> +apiVersion: v1
已加

2022-05-18 15:09 UTC, hongqn commented on lain_cli/chart_template/templates/deployment.yaml
> +kind: PersistentVolumeClaim
残留代码已删

2022-05-18 15:09 UTC, hongqn commented on lain_cli/chart_template/values.yaml.j2
> +#     storageClassName: my-sc
改为了 `juicefs-sc` ，示例 pvc 名也改为了 `juicefs-pvc`

2022-05-18 15:10 UTC, hongqn commented on lain_cli/chart_template/values.yaml.j2
> +#         storage: 10Pi
已改为 1Gi

2022-05-18 15:10 UTC, hongqn commented on lain_cli/chart_template/values.yaml.j2
> +# 在 persistentVolumeClaims 里定义的 claim 都会自动创建一个同名的 volume ，不用在这里写了。
已挪到 pvc 上方

2022-05-18 15:15 UTC, hongqn commented on lain_cli/chart_template/templates/deployment.yaml
> +            claimName: {{ $.Release.Name }}-{{ $pvcName }}
这个字符串拼接在 pvc.yaml 中定义，作为资源名，在这里使用名字引用。感觉两个都在 templates 里完成比较合适些，属于 template 封装掉的细节。

2022-05-20 02:48 UTC, timfeirg commented on lain_cli/chart_template/templates/pvc.yaml
> +  {{- if hasKey $pvc "useClusterSpec" }}
useClusterSpec 相关逻辑也属于需要清理掉的旧代码, 对吧?

2022-05-20 02:52 UTC, timfeirg commented on lain_cli/chart_template/values.yaml.j2
> +# # 如果你使用了 PersistentVolume (SA 会告诉你是不是用了这个），那么需要在这里写上 persistentVolumeClaims 来
注释有点问题, 我理解带有 persistence 的 volume, 都属于 persistent volume. 从这个意义说, 像什么 hostPath 或者 local-pv, 都算是一种类型的 pv. jfs 也不例外.

因此这里不妨直接向用户介绍, 如果需要用 jfs csi 的话, 可以直接按下方示范声明 pvc, 就会追加到 volumes 下, 无需重复声明. 之类的.

2022-05-20 02:54 UTC, timfeirg commented
如果评论的部分无争议, 修改以后自行测通合并即可. 我将你加入了 collaborator @hongqn

2022-05-23 07:04 UTC, hongqn commented on lain_cli/chart_template/templates/pvc.yaml
> +  {{- if hasKey $pvc "useClusterSpec" }}
清理了

2022-05-23 07:04 UTC, hongqn commented on lain_cli/chart_template/values.yaml.j2
> +# # 如果你使用了 PersistentVolume (SA 会告诉你是不是用了这个），那么需要在这里写上 persistentVolumeClaims 来
修改了注释

2022-05-23 07:08 UTC, hongqn commented
我似乎还没有 merge 权限，可能是因为有 review request pending

2022-05-23 07:11 UTC, hongqn commented
另外，由于涉及到 chart template 更新，应该要升级 chart version 吧。目前 version 是 0.1.11 。本 pr 这种新 feature 支持，是建议升到 0.2.0 还是 0.1.12 ?

2022-05-23 09:30 UTC, merged

2022-05-23 09:58 UTC, timfeirg commented
chart version 的作用是强制升级, 也就是如果不 lain init --template-only 的话, lain lint 会直接报错. 

lain 的维护原则是没有重大 bug, 或者我所属的团队没有需要强推的 feature 更新, 就不去主动升级 chart version @hongqn